version: 0.2

env:
  variables:
    KNOWN_BUCKET: lambda-dev-eu-west-1
    PY_VERSION: 3.8
    CASES_FOLDER: test-cases
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: "$(echo $PY_VERSION)"
    commands:
      - export PY_FULL_VERSION=`python --version| awk '{print $NF}'`
      - export PATH=/root/.pyenv/versions/${PY_FULL_VERSION}/bin:${PATH}
      - pip install pip -U || curl -s https://bootstrap.pypa.io/get-pip.py | python
      - pip install behave
      - python setup.py install

  build:
    commands:
      - export CASE_ID=case01
      - export CASE_PATH=${PWD}/${CASES_FOLDER}/${CASE_ID} && echo $CASE_PATH && mkdir -p $CASE_PATH
      - ecs_composex-vpc -d ${CASE_PATH} -o root.yml -b ${CFN_TPL_BUCKET} --single-nat
      - export CASE_ID=case02
      - export CASE_PATH=${PWD}/${CASES_FOLDER}/${CASE_ID} && echo $CASE_PATH && mkdir -p $CASE_PATH
      - ecs_composex-vpc -d ${CASE_PATH} -o root.yml -b ${CFN_TPL_BUCKET}
      - ls -lR ${PWD}/${CASES_FOLDER}/

artifacts:
  files:
    - '**/*.yml'
    - '**/*.json'
  base-directory: "$(echo $CASES_FOLDER)"
  name: "${echo $CASES_FOLDER}"
